/* 
GET: كلمة مفتاحية في HTTP تستخدم لطلب البيانات من الخادم. 
*/
GET http://localhost:5076
/* 
http: بروتوكول نقل النص الفائق، يستخدم لنقل البيانات عبر الشبكة.
localhost: يشير إلى الجهاز المحلي الذي يعمل عليه التطبيق.
5076: رقم المنفذ الذي يستمع عليه التطبيق للطلبات.
*/

### 
/* 
GET: كلمة مفتاحية في HTTP تستخدم لطلب البيانات من الخادم.
*/
GET http://localhost:5076/downloads
/* 
/downloads: المسار الذي يتم طلب البيانات منه.
*/

### 
/* 
PUT: كلمة مفتاحية في HTTP تستخدم لإرسال بيانات إلى الخادم لتحديث مورد موجود.
*/
PUT http://localhost:5076/
/* 
/: المسار الجذر الذي يتم إرسال البيانات إليه.
*/

### 
/* 
PUT: كلمة مفتاحية في HTTP تستخدم لإرسال بيانات إلى الخادم لتحديث مورد موجود.
*/
PUT http://localhost:5076/hello
/* 
/hello: مسار مخصص يتم إرسال البيانات إليه.
*/

### 
/* 
DELETE: كلمة مفتاحية في HTTP تستخدم لحذف مورد موجود على الخادم.
*/
DELETE http://localhost:5076/
/* 
/: المسار الجذر الذي يتم إرسال طلب الحذف إليه.
*/

### 
/* 
POST: كلمة مفتاحية في HTTP تستخدم لإرسال بيانات إلى الخادم لإنشاء مورد جديد.
*/
POST http://localhost:5076/
/* 
/: المسار الجذر الذي يتم إرسال البيانات إليه لإنشاء مورد جديد.
*/