GET http://localhost:5093/todos

###

POST http://localhost:5093/todos
Content-Type: application/json

{
    "id": 2,
    "name": "My new todo2",
    "dueDate": "2026-12-31",
    "isComplete": false
}

### 

GET http://localhost:5093/todos/2

###

DELETE http://localhost:5093/todos/1