GET http://localhost:5093/todos

###

POST http://localhost:5093/todos
Content-Type: application/json

{
    "id": 3,
    "name": "My new todo",
    "dueDate": "2025-12-31",
    "isComplete": true
}

### 

GET http://localhost:5093/todos/2

###

DELETE http://localhost:5093/todos/1

###
GET http://localhost:5093/tasks/1